### ISSUE TITLE
problem at build

### ISSUE THREAD

**Issue by rferrali** [sverhoeven/docker-cartodb#47]
Hi, 
It seems the build is failing. I've run` docker build -t=sverhoeven/cartodb docker-cartodb/` and I get the following error at step 23/49: 

```
RUN service postgresql start && /bin/su postgres -c       /tmp/template_postgis.sh && service postgresql stop
 ---> Running in 67a91db53068
 * Starting PostgreSQL 10 database server
   ...done.
bash: /tmp/template_postgis.sh: /bin/bash^M: bad interpreter: No such file or directory
The command '/bin/sh -c service postgresql start && /bin/su postgres -c       /tmp/template_postgis.sh && service postgresql stop' returned a non-zero code: 126
```

**Comment by sverhoeven** [comment]
Hmm, I am unable to reproduce this error. It builds correctly on my local machine and on Docker Hub.

```
Step 23/49 : RUN service postgresql start && /bin/su postgres -c       /tmp/template_postgis.sh && service postgresql stop


 ---> Running in 71571d79a9f8

 * Starting PostgreSQL 10 database server

   ...done.

[91mError: [0m
[91mpg_wrapper: createlang was not found in /usr/lib/postgresql/10/bin[0m
[91m
[0m
UPDATE 1
```

Are you using a up to date clone of https://github.com/sverhoeven/docker-cartodb.git and latest version of `ubuntu:18.04` Docker image? 

Also try to build without cache using `docker build -t=sverhoeven/cartodb --no-cache docker-cartodb/`

**Comment by rferrali** [comment]
Thank you for your quick response. Weird! I believe I did everything you suggested, but get the exact same error. I'm new to Docker, there might be something obvious I'm missing. 
```
docker pull ubuntu
git clone https://github.com/sverhoeven/docker-cartodb.git
docker build -t=sverhoeven/cartodb --no-cache docker-cartodb/
```

**Comment by pjduplooy** [comment]
sverhoefen and rferrali.

Found the solution thanks to webodm project.

When using the git clone command append it with the following at the end of the line:

--config core.autocrlf=input

There is a difference of how git on Windows and the the nix'e (Linux and OSX) handle linefeeds at the end of text files etc.

I am running Windows.

sverhoefen

Could you please update the docs with this.  Could you also please update the docs so that for Windows users one has to use the docker ip address, usually 192.168.99.100 in stead of 127.0.1.1.

Hope this helps.

Pieter

**Comment by rferrali** [comment]
Thank you Pieter, that solved my problem.
