### ISSUE TITLE
Problems filling the internal geocoder

### ISSUE THREAD

**Issue by christophekey** [sverhoeven/docker-cartodb#57]
Docker image all set up, tested and working. 
Go to fill the internal geocoder 
Run:

docker exec -ti <carto docker container id> bash -c /cartodb/script/fill_geocoder.sh

from clean docker container Varnish error - log - https://gist.github.com/christophekey/853ad3df5e9d1d83550aa13c724b726b

problem seems to result from Varnish and not respecting timeouts, so kill running varnish processes run again, completes and reports - ** Everything OK **

log - https://gist.github.com/christophekey/5805653cab2ba4b40c503d5c7a6171f9

restart the container - geocoder only returns _null_ in the geom table when running a geocode of IP to lat, lon.

Tried with a new clean build, issue persists.

**Comment by sverhoeven** [comment]
It has been a while since I used the geocoder.
Just started a freshly build imager and ran the fill_geocoder.sh script
I ignored the varnish warnings.

I tried `151.101.0.81` in the name column of a empty map and it got geocoded to `{"type":"Point","coordinates":[-71.4652,42.9885]}`.

How did you restart? Stop/start or kill+rm/run?

**Comment by christophekey** [comment]
Hey Stefan, 
Started from scratch, new VM on hypervisor, added --pull into the docker compose when building, ran the geocoder scripts again, reboot of the VM and things are working. I must have had a hiccup along the way ! thank you.
