### ISSUE TITLE
unable to upload database

### ISSUE THREAD

**Issue by sandeepgadhwal** [sverhoeven/docker-cartodb#8]
i am unable to upload any dataset error which i am getting is that it shows pending upload for sometime and after that this code 8063ae73-3bb8-4cf5-9b7f-99338ba6c871

anyway it worked it worked for the first time but now its always getting stuck what can be the reason.

**Comment by dherrebout** [comment]
Unfortunately I am experiencing this issue as well, the first upload after installing seems to work but after that datasets won't load anymore.

**Comment by sverhoeven** [comment]
I just uploaded a new version to Docker Hub. Could you try again?

**Comment by dherrebout** [comment]
Thank you for the new version, I appreciate your effort. However, although I deployed the new container on a new instance, uploading data still doesn't seem to work. I've tried to upload a package of only 20mbs, which does work completely on the hosted version of carto on carto.com so the package is not broken, but this installation keeps importing forever. It does not return any import errors, but it leads to the webserver breaking in some way. After the attempted data import the whole carto server times out with a 504, and none of the pages load anymore. Even SSHing into the server is not possible anymore. I wish I could provide you with more information, but since the server breaks I can't retrieve any logs as well.

**Comment by dherrebout** [comment]
After rebooting the server and trying again, the first time connecting a dataset worked, the second time resulted in an error:

![image](https://user-images.githubusercontent.com/28226077/27769930-db84c340-5f35-11e7-8fce-1a26ec05354c.png)

**Comment by dherrebout** [comment]
I am still getting the same errors but now at least the server does not crash anymore, which possibly means I could trace some error logs. The only problem is I don't know where I could find them. If you have any idea how I could trace this error, please let me know!

**Comment by sandeepgadhwal** [comment]
out of topic question : Can we use this image in production ?
if not can you suggest any changes that can help me make this image production ready.

**Comment by dherrebout** [comment]
Yes you can, by following the exact instructions in the readme. Did scaling up the server resolve the data upload for you as well? If it did, this issue can be closed.

**Comment by sverhoeven** [comment]
You can, make sure to change the password of the `dev` and `admin4example` accounts.

Also the internals are configured for the least amount of setup hassle, for example the Postgresql database requires no password to login and the services are running in development mode to allow for unencrypted connections.
See https://github.com/NLeSC/eEcology-CartoDB/blob/master/setup.md where I do some fortifying.

**Comment by sandeepgadhwal** [comment]
I recieved error while uploading database but the database was uploaded successfully. i dont know why error is still there. anyway its working so you can close the issue.
